#!/bin/bash

# create and format the image file, if it doesn't exist
if ! test -f "os.img"; then
	dd of=os.img if=/dev/zero bs=1M count=33 status=none
fi

# format the image as FAT32 with size 33MB
mformat -F -h 64 -s 32 -t 33 -c 1 -i os.img ::

# make the directories
mmd -D s -i os.img ::/EFI
mmd -D s -i os.img ::/EFI/BOOT

# copy the required files
mcopy -D o -i os.img image/EFI/BOOT/BOOTX64.EFI ::/EFI/BOOT
mcopy -D o -i os.img image/tomatboot.cfg ::
mcopy -D o -i os.img image/kernel.elf ::

