#!/bin/bash

KERNEL="kernel/kernel.elf"

# copy limine files
cp -n thirdparty/limine-bin/limine.sys image/boot/limine.sys
cp -n thirdparty/limine-bin/limine-cd.bin image/boot/limine-cd.bin
cp -n thirdparty/limine-bin/limine-eltorito-efi.bin image/boot/limine-efi.bin
mkdir -p image/EFI/BOOT && cp -n thirdparty/limine-bin/BOOTX64.EFI image/EFI/BOOT/BOOTX64.EFI

# copy the kernel
cp $KERNEL image/boot/kernel.elf

# build the iso
xorriso -as mkisofs \
  -J -joliet-long \
  -rock \
  -b boot/limine-cd.bin \
  -c boot/limine-cd.cat \
  -no-emul-boot -boot-load-size 4 -boot-info-table \
  -eltorito-alt-boot \
  -e boot/limine-efi.bin \
  -no-emul-boot -isohybrid-gpt-basdat \
  image \
  -o os.iso
